# Generated by Django 5.1.1 on 2024-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_delete_newslettersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
