# Generated by Django 5.1.1 on 2024-09-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_newsletter_created_at_alter_newsletter_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='NewsletterSubscription',
        ),
    ]
